### PR TITLE
Lots of changes/enhancements: json + http logging + opt-in flag + better rate limit handling

### PR DESCRIPTION
**Pull request by zenspider**
Signed-off-by: Ryan Davis <zenspider@chef.io>

### CODE REVIEW

**Comment by zenspider** [comment]
Might want to review per commit... I'm happy to rewrite to roll out some of the earlier stuff once I dropped toml for yaml.

**Comment by lamont-granquist** [comment]
yr subject line sez "json"

**Comment by thommay** [comment]
TOML to YAML seems like a backward step; what's the reasoning?

**Comment by thommay** [comment]
@zenspider I'm probably not going to take this as is. If you want yaml support, please could you:
1. explain why
2. continue to support toml as well

And then break out the other features separately.

**Pull request closed without merging**
